title: "Bala Mahadevan – Technical Documentation Portfolio"
description: "Technical Writer | API Docs | SaaS | Release Notes | User Guides | Implementation Guides | Configuration Guides | SOPs"
theme: jekyll-theme-slate
markdown: kramdown
